convert:
	convert -alpha remove -alpha off RippleCarry.ps RippleCarry.png
	convert -alpha remove -alpha off XORAdd.ps XORAdd.png
	convert -alpha remove -alpha off GPAdd.ps GPAdd.png
	convert -alpha remove -alpha off Merge.ps Merge.png
	convert -alpha remove -alpha off PrefixTree8.ps PrefixTree8.png
	convert -alpha remove -alpha off PrefixTree32.ps PrefixTree32.png
	convert -alpha remove -alpha off PrefixAdder.ps PrefixAdder.png
	convert -alpha remove -alpha off PrefixTreeRecur.ps PrefixTreeRecur.png
