convert:
	convert -alpha remove -alpha off AndTree.ps             AndTree.png
	convert -alpha remove -alpha off EdgeDetection.ps       EdgeDetection.png
	convert -alpha remove -alpha off OrTree6.ps             OrTree6.png
	convert -alpha remove -alpha off OrTree7.ps             OrTree7.png
	convert -alpha remove -alpha off OrTree.ps              OrTree.png
	convert -alpha remove -alpha off OrTreeRev.ps           OrTreeRev.png
	convert -alpha remove -alpha off PEOneHotAll.ps         PEOneHotAll.png
	convert -alpha remove -alpha off PEOneHot.ps            PEOneHot.png
	convert -alpha remove -alpha off PrefixAnd.ps           PrefixAnd.png
	convert -alpha remove -alpha off PrefixOr.ps            PrefixOr.png
	convert -alpha remove -alpha off PrefixTree32.ps        PrefixTree32.png
	convert -alpha remove -alpha off PrefixTree8.ps         PrefixTree8.png
	convert -alpha remove -alpha off TwoComplementAll.ps    TwoComplementAll.png  
	convert -alpha remove -alpha off TwoComplement.ps       TwoComplement.png     
	convert -alpha remove -alpha off TwoComplementSteps.ps  TwoComplementSteps.png















