convert:
	convert -alpha remove -alpha off ValidRecursion.ps ValidRecursion.png
	convert -alpha remove -alpha off Mux.ps            Mux.png 
	convert -alpha remove -alpha off Mux8.ps           Mux8.png
	convert -alpha remove -alpha off MuxN.ps           MuxN.png
	convert -alpha remove -alpha off Mux16Ext.ps       Mux16Ext.png
	convert -alpha remove -alpha off PE.ps             PE.png
	convert -alpha remove -alpha off PEBase.ps         PEBase.png
	convert -alpha remove -alpha off PE8.ps            PE8.png
	convert -alpha remove -alpha off PEN.ps            PEN.png
	convert -alpha remove -alpha off PE16Ext.ps        PE16Ext.png
