convert:
	convert -alpha remove -alpha off BitComp.ps          BitComp.png
	convert -alpha remove -alpha off Comp2.ps            Comp2.png
	convert -alpha remove -alpha off Comp4.ps            Comp4.png
	convert -alpha remove -alpha off Comp8.ps            Comp8.png
	convert -alpha remove -alpha off CompFull.ps         CompFull.png
	convert -alpha remove -alpha off EqComp.ps           EqComp.png
	convert -alpha remove -alpha off IneqCompExamples.ps IneqCompExamples.png
	convert -alpha remove -alpha off CompCases.ps        CompCases.png
